### PR TITLE
handle multipart/form-data's text/*.

### PR DESCRIPTION
**Pull request by pocket7878**
I think it is better to treat 'text/*' in multipart/form-data into text not pure vector-stream.

### CODE REVIEW

**Comment by pocket7878** [comment]
~~Sorry.. maybe this won't work until https://github.com/cl-babel/babel/pull/25 merged into babel.~~
Converting charset string into keyword to deal with babel.

**Comment by fukamachi** [comment]
What is the status of this request?

**Comment by pocket7878** [comment]
@fukamachi Sorry for my late reply. I sent PR to cl-babel 
https://github.com/cl-babel/babel/pull/25
to support lookup encoding by name on cl-babel. 

I still waiting merging PR on cl-babel... But maybe it takes very long..

**Comment by fukamachi** [comment]
The latest Http-Body has this feature. Closing.

**Pull request closed without merging**
