### PR TITLE
Hoist dbi sql queries into configurable parameters

### PR DESCRIPTION
**Pull request by mavericksy**
The sql queries in the DBI store are not accessible and enforce the structure of the database table for sessions.
This PR hoists the queries into package local parameters and allows them to be configured via &key function parameters to DBI.
ie.

### CODE REVIEW

**Comment by fukamachi** [comment]
What do you need it for?
It's too low-level to give users access since it's not a kind of parameter that must be configured for each application.

**Comment by mavericksy** [comment]
In one instance the sessions table already exists and lack needs to conform to the already created table.
Another instance is the sessions are handled by functions in the DB, so direct SQL  queries will not work to handle the sessions table.

**Comment by mavericksy** [comment]
BTW the queries have defaults.
Queries do not have to be setup to use the session dbi.
The original queries will be honoured and used

**Comment by fukamachi** [comment]
I see your point. You have a session table with slightly different structures and want to customize the queries thrown in the code.
However, I still don't think it's difficult for other users to use, in the sense that it must be a format-control string that takes arguments in the exact same order.
How about simply adding parameters of the column names (id, session_data) to access?

**Comment by mavericksy** [comment]
> I see your point. You have a session table with slightly different structures and want to customize the queries thrown in the code. However, I still don't think it's difficult for other users to use, in the sense that it must be a format-control string that takes arguments in the exact same order. How about simply adding parameters of the column names (id, session_data) to access?

Ok, just controlling and being able to change the column names will be safer and easier to use.
Will update PR soon.

**Comment by mavericksy** [comment]
Changed format strings to accept dbi-store configurable column names.
Just as table_name is used, so are session_data and id.
Added README as well

**Review by fukamachi — APPROVED** [review]

**Comment by fukamachi** [comment]
Thanks!

**Pull request merged**
